FROM node:20.11.1-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

ENV AWS_DEFAULT_REGION=us-east-1

ENV localstack_endpoint='http://localstack:4566'

CMD ["node", "serviceSetup.js"]